name: Linux (dotnet build and test)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  os-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
            6.0.x
            7.0.x
            8.0.x
      - name: Start RabbitMQ
        uses: Namoshek/rabbitmq-github-action@v1
        with:
          version: '3.8.9'
          ports: '1883:1883 8883:8883'
          definitions: ${{ github.workspace }}/.ci/definitions.json
      - name: Restore dependencies
        run: dotnet restore ./src/CSharp/EasyMicroservices.MessageBrokers.sln
      - name: Build
        run: dotnet build ./src/CSharp/EasyMicroservices.MessageBrokers.sln --no-restore
      - name: Test
        run:  |
          dotnet test ./src/CSharp/EasyMicroservices.MessageBrokers.sln --no-build --verbosity normal -f net6.0
          dotnet test ./src/CSharp/EasyMicroservices.MessageBrokers.sln --no-build --verbosity normal -f net7.0
          dotnet test ./src/CSharp/EasyMicroservices.MessageBrokers.sln --no-build --verbosity normal -f net8.0
